version: '3'

services:
  
  dhcpd:
    image: networkboot/dhcpd:latest
    deploy:
      replicas: 1
    volumes:
      - "./data/dhcpd:/data"
    environment:
      IFACE: eth0

  radius:
    image: freeradius/freeradius-server:latest
    deploy:
      replicas: 1
    volumes:
      - "./data/freeradius/:/etc/freeradius"
    command:
      - freeradius
      - -tfxxxxxl
      - stdout

  controller:
    image: ${CONTROLLER_IMAGE:-onosproject/onos:1.13.1}
    deploy:
      replicas: 1
    ports:
      - "6653:6653"
      - "8101:8101"
      - "8181:8181"
      - "8080:8080"
    environment:
      ONOS_APPS: "openflow,fwd,aaa"

  aaa:
    image: aaa:local
    deploy:
      replicas: 1
    ports:
      - "8005:8005"
    environment:
      LOG_LEVEL: "error"
      RADIUS_AT: "radius:1812"
      LISTEN_ON: ":8005"
      OFTEE_API: "http://oftee:8000"
      SHARED_SECRET: "SECRET"
      RADIUS_TIMEOUT: "10s"

  relay:
    image: dhcp-relay:local
    deploy:
      replicas: 1
    ports:
      - "5000:5000"

  oftee:
    image: oftee:local
    deploy:
      replicas: 1
    ports:
      - "6654:6654"
      - "8000:8000"
    environment:
      LISTEN_ON: ":6654"
      API_ON: ":8000"
      PROXY_TO: "controller:6653"
      LOG_LEVEL: "debug"
      SHARE_CONNECTIONS: "true"
      TEE_TO: "dl_type=0x888e;action=http://aaa:8005/aaa/eap,dl_type=0x0800;action=http://relay:5000/packet"
      TEE_RAW: "false"

  host:
    image: host:local
    deploy:
      replicas: 1
    entrypoint:
      - sleep
      - 365d
    volumes:
      - "./data/wpa_supplicant.conf:/etc/wpa_supplicant/wpa_supplicant.conf"
